server {
    listen 80;
    server_name demo.devprattle.com;

    # Redirect HTTP to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name demo.devprattle.com;

    ssl_certificate /etc/letsencrypt/live/demo.devprattle.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/demo.devprattle.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://web:8000; # Proxy to Django web service
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /media/ {
        alias /usr/src/django_backend/media/;
    }

    location /static/ {
        alias /usr/src/django_backend/static/;
    }

    location ~^/ws/ {
        proxy_pass http://daphne:8002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
